<?php

use App\Http\Controllers\Api\V1\FleetController;
use App\Http\Controllers\Api\V1\FranchiseController;
use App\Http\Controllers\Api\V1\LiveMapController;
use App\Http\Controllers\Api\V1\OpsController;
use App\Http\Controllers\Api\V1\PaymentController;
use App\Http\Controllers\Api\V1\PlatformSessionController;
use App\Http\Controllers\Api\V1\StateHeadController;
use App\Http\Controllers\Api\V1\CustomerExperienceController;
use App\Http\Controllers\Api\V1\CouponController;
use App\Http\Controllers\Api\V1\AdvertisingController;
use App\Http\Controllers\Api\V1\WalletController;
use App\Http\Controllers\Api\V1\SafetyController;
use App\Http\Controllers\Api\V1\SupportController;
use App\Http\Controllers\Api\V1\NotificationsController;
use App\Http\Controllers\Api\V1\PlacesController;
use App\Http\Controllers\Api\V1\ReportsController;
use App\Http\Controllers\Api\V1\RideController;
use Illuminate\Support\Facades\Route;

Route::post('/v1/payments/webhooks/{provider}', [PaymentController::class, 'webhook']);
Route::get('/v1/safety/catalog', [SafetyController::class, 'catalog']);
Route::get('/v1/safety/share/{token}', [SafetyController::class, 'publicShare']);
Route::get('/v1/support/catalog', [SupportController::class, 'catalog']);
Route::get('/v1/notifications/catalog', [NotificationsController::class, 'catalog']);

Route::get('/v1/places/autocomplete', [PlacesController::class, 'autocomplete']);
Route::get('/v1/places/details', [PlacesController::class, 'details']);
Route::post('/v1/places/directions', [PlacesController::class, 'directions']);
Route::get('/v1/rides/catalog', [RideController::class, 'catalog']);
Route::post('/v1/rides/quote', [RideController::class, 'quote']);

Route::middleware(['web', 'customer.api'])->prefix('v1')->group(function () {
    Route::post('/rides/bookings', [RideController::class, 'store']);
    Route::get('/rides/bookings/{id}', [RideController::class, 'show']);
    Route::post('/rides/bookings/{id}/payments', [RideController::class, 'pay']);
});

Route::middleware(['web', 'auth'])->prefix('v1')->group(function () {
    Route::get('/platform/session', [PlatformSessionController::class, 'show']);
    Route::get('/platform/health', [PlatformSessionController::class, 'platformHealth']);

    Route::get('/live/map', [LiveMapController::class, 'snapshot']);
    Route::post('/live/fix', [LiveMapController::class, 'ingest']);
    Route::get('/live/me', [LiveMapController::class, 'mine']);
    Route::get('/live/bookings/{id}', [LiveMapController::class, 'booking']);

    Route::get('/fleet', [FleetController::class, 'overview']);
    Route::get('/fleet/vehicles', [FleetController::class, 'vehicles']);
    Route::post('/fleet/vehicles', [FleetController::class, 'storeVehicle']);
    Route::get('/fleet/vehicles/{id}', [FleetController::class, 'showVehicle']);
    Route::patch('/fleet/vehicles/{id}', [FleetController::class, 'updateVehicle']);
    Route::post('/fleet/vehicles/{id}/documents', [FleetController::class, 'storeVehicleDocument']);
    Route::get('/fleet/drivers', [FleetController::class, 'drivers']);
    Route::post('/fleet/drivers', [FleetController::class, 'storeDriver']);
    Route::get('/fleet/drivers/{id}', [FleetController::class, 'showDriver']);
    Route::post('/fleet/drivers/{id}/assign', [FleetController::class, 'assign']);
    Route::post('/fleet/drivers/{id}/unassign', [FleetController::class, 'unassign']);
    Route::delete('/fleet/drivers/{id}', [FleetController::class, 'destroyDriver']);
    Route::patch('/fleet/drivers/{id}/kyc', [FleetController::class, 'driverKyc']);
    Route::post('/fleet/drivers/{id}/documents', [FleetController::class, 'driverDocument']);
    Route::patch('/fleet/drivers/{id}/status', [FleetController::class, 'driverStatus']);
    Route::get('/fleet/trips', [FleetController::class, 'trips']);
    Route::get('/fleet/reports', [FleetController::class, 'reports']);

    Route::get('/franchises', [FranchiseController::class, 'index']);
    Route::post('/franchises', [FranchiseController::class, 'store']);
    Route::get('/franchises/{id}', [FranchiseController::class, 'show']);
    Route::patch('/franchises/{id}/lifecycle', [FranchiseController::class, 'lifecycle']);
    Route::patch('/franchises/{id}/kyc', [FranchiseController::class, 'kyc']);
    Route::post('/franchises/{id}/documents', [FranchiseController::class, 'document']);
    Route::post('/franchises/{id}/agreement', [FranchiseController::class, 'agreement']);
    Route::post('/franchises/{id}/fees', [FranchiseController::class, 'fee']);
    Route::post('/franchises/{id}/fees/{feeId}/pay', [FranchiseController::class, 'payFee']);
    Route::post('/franchises/{id}/renewals', [FranchiseController::class, 'renewal']);
    Route::patch('/franchises/{id}/renewals/{renewalId}', [FranchiseController::class, 'decideRenewal']);
    Route::patch('/franchises/{id}/commission', [FranchiseController::class, 'commission']);
    Route::patch('/franchises/{id}/territory', [FranchiseController::class, 'territory']);

    Route::get('/payments/catalog', [PaymentController::class, 'catalog']);
    Route::get('/payments', [PaymentController::class, 'index']);
    Route::post('/payments', [PaymentController::class, 'store']);
    Route::get('/payments/invoices', [PaymentController::class, 'invoices']);
    Route::get('/payments/invoices/{id}', [PaymentController::class, 'invoice']);
    Route::post('/payments/{id}/client-success', [PaymentController::class, 'clientSuccess']);
    Route::post('/payments/{id}/confirm-cash', [PaymentController::class, 'confirmCash']);
    Route::post('/payments/{id}/fail', [PaymentController::class, 'fail']);
    Route::post('/payments/{id}/refund/{step}', [PaymentController::class, 'refundStep']);
    Route::post('/payments/{id}/refund', [PaymentController::class, 'refund']);
    Route::get('/payments/{id}', [PaymentController::class, 'show']);
    Route::get('/me/catalog', [CustomerExperienceController::class, 'catalog']);
    Route::get('/me', [CustomerExperienceController::class, 'dashboard']);
    Route::patch('/me/profile', [CustomerExperienceController::class, 'updateProfile']);
    Route::patch('/me/emergency', [CustomerExperienceController::class, 'updateEmergency']);
    Route::post('/me/family', [CustomerExperienceController::class, 'storeFamily']);
    Route::delete('/me/family/{id}', [CustomerExperienceController::class, 'destroyFamily']);
    Route::post('/me/places', [CustomerExperienceController::class, 'storePlace']);
    Route::delete('/me/places/{id}', [CustomerExperienceController::class, 'destroyPlace']);
    Route::post('/me/complaints', [CustomerExperienceController::class, 'storeComplaint']);
    Route::post('/me/ratings', [CustomerExperienceController::class, 'storeRating']);
    Route::post('/me/notifications/{id}/read', [CustomerExperienceController::class, 'readNotification']);
    Route::get('/me/{section}', [CustomerExperienceController::class, 'section']);
    Route::get('/safety/me', [SafetyController::class, 'me']);
    Route::get('/safety/contacts', [SafetyController::class, 'contacts']);
    Route::patch('/safety/emergency-contact', [SafetyController::class, 'saveEmergency']);
    Route::post('/safety/emergency-contact', [SafetyController::class, 'saveEmergency']);
    Route::delete('/safety/contacts/{id}', [SafetyController::class, 'destroyContact']);
    Route::get('/safety/sos', [SafetyController::class, 'sosPeek']);
    Route::post('/safety/sos', [SafetyController::class, 'sos']);
    Route::post('/safety/share', [SafetyController::class, 'share']);
    Route::get('/safety/bookings/{id}/verify', [SafetyController::class, 'verify']);
    Route::post('/safety/bookings/{id}/otp', [SafetyController::class, 'confirmOtp']);
    Route::get('/safety/incidents', [SafetyController::class, 'incidents']);
    Route::patch('/safety/incidents/{id}', [SafetyController::class, 'review']);
    Route::get('/safety/incidents/{id}', [SafetyController::class, 'show']);
    Route::get('/support/tickets', [SupportController::class, 'index']);
    Route::post('/support/tickets', [SupportController::class, 'store']);
    Route::post('/support/tickets/{id}/assign', [SupportController::class, 'assign']);
    Route::post('/support/tickets/{id}/replies', [SupportController::class, 'reply']);
    Route::post('/support/tickets/{id}/attachments', [SupportController::class, 'attach']);
    Route::get('/support/tickets/{id}/attachments/{attachmentId}', [SupportController::class, 'file']);
    Route::patch('/support/tickets/{id}', [SupportController::class, 'update']);
    Route::get('/support/tickets/{id}', [SupportController::class, 'show']);
    Route::get('/notifications', [NotificationsController::class, 'index']);
    Route::get('/notifications/deliveries', [NotificationsController::class, 'deliveries']);
    Route::post('/notifications/announce', [NotificationsController::class, 'announce']);
    Route::post('/notifications/dispatch', [NotificationsController::class, 'dispatch']);
    Route::get('/coupons/catalog', [CouponController::class, 'catalog']);
    Route::get('/coupons/offers', [CouponController::class, 'offers']);
    Route::post('/coupons/preview', [CouponController::class, 'preview']);
    Route::post('/coupons/apply', [CouponController::class, 'apply']);
    Route::get('/loyalty', [CouponController::class, 'loyalty']);
    Route::post('/loyalty/earn', [CouponController::class, 'earnLoyalty']);
    Route::post('/loyalty/preview', [CouponController::class, 'previewLoyalty']);
    Route::get('/coupons', [CouponController::class, 'index']);
    Route::post('/coupons', [CouponController::class, 'store']);
    Route::patch('/coupons/{id}', [CouponController::class, 'update']);
    Route::get('/coupons/{id}', [CouponController::class, 'show']);
    Route::get('/ads/catalog', [AdvertisingController::class, 'catalog']);
    Route::get('/ads/serve', [AdvertisingController::class, 'serve']);
    Route::get('/ads', [AdvertisingController::class, 'index']);
    Route::post('/ads', [AdvertisingController::class, 'store']);
    Route::get('/ads/{id}/banner', [AdvertisingController::class, 'bannerFile']);
    Route::post('/ads/{id}/banner', [AdvertisingController::class, 'banner']);
    Route::post('/ads/{id}/review', [AdvertisingController::class, 'review']);
    Route::post('/ads/{id}/pause', [AdvertisingController::class, 'pause']);
    Route::post('/ads/{id}/resume', [AdvertisingController::class, 'resume']);
    Route::post('/ads/{id}/impression', [AdvertisingController::class, 'impression']);
    Route::post('/ads/{id}/click', [AdvertisingController::class, 'click']);
    Route::patch('/ads/{id}', [AdvertisingController::class, 'update']);
    Route::get('/ads/{id}', [AdvertisingController::class, 'show']);
    Route::get('/wallets', [WalletController::class, 'index']);
    Route::get('/wallets/ledger', [WalletController::class, 'ledger']);
    Route::get('/commission', [WalletController::class, 'policy']);
    Route::patch('/commission', [WalletController::class, 'updatePolicy']);
    Route::post('/wallets/ledger', [WalletController::class, 'post']);
    Route::post('/bookings/{id}/settle', [WalletController::class, 'settle']);
    Route::get('/wallets/{id}', [WalletController::class, 'show']);
    Route::get('/reports', [ReportsController::class, 'catalog']);
    Route::get('/reports/{report}/export', [ReportsController::class, 'export']);
    Route::get('/reports/{report}', [ReportsController::class, 'show']);
    Route::get('/ops/dashboard', [OpsController::class, 'dashboard']);
    Route::get('/state', [StateHeadController::class, 'dashboard']);
    Route::post('/state/district-heads', [StateHeadController::class, 'storeDistrictHead']);
    Route::post('/state/franchises', [StateHeadController::class, 'storeFranchise']);
    Route::post('/state/notifications', [StateHeadController::class, 'notify']);
    Route::get('/state/{section}', [StateHeadController::class, 'show']);
    Route::get('/ops/{module}/export', [OpsController::class, 'export']);
    Route::get('/ops/users/{id}', [OpsController::class, 'showUser']);
    Route::post('/ops/users', [OpsController::class, 'storeUser']);
    Route::patch('/ops/users/{id}', [OpsController::class, 'patchUser']);
    Route::get('/ops/bookings/{id}', [OpsController::class, 'showBooking']);
    Route::patch('/ops/drivers/{id}', [OpsController::class, 'patchDriver']);
    Route::post('/ops/notifications/announce', [OpsController::class, 'announce']);
    Route::get('/ops/{module}', [OpsController::class, 'index']);
});
